FROM ubuntu:16.04
MAINTAINER hidetomo

# create user
COPY root_pass root_pass
RUN echo "root:$(cat root_pass)" | chpasswd
RUN useradd hidetomo
RUN mkdir /home/hidetomo && chown hidetomo:hidetomo /home/hidetomo
COPY hidetomo_pass hidetomo_pass
RUN echo "hidetomo:$(cat hidetomo_pass)" | chpasswd

# init apt-get
RUN apt-get -y update

# sudo
RUN apt-get -y install sudo
RUN echo "hidetomo ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

# change user and dir
USER hidetomo
WORKDIR /home/hidetomo
ENV HOME /home/hidetomo

# alias
RUN echo "alias ls='ls --color'" >> .bashrc

# ssh key
COPY id_rsa .ssh/id_rsa
RUN sudo tr \\r \\n <.ssh/id_rsa> tmp && sudo mv tmp .ssh/id_rsa
RUN sudo chown hidetomo:hidetomo .ssh/id_rsa
RUN chmod 600 .ssh/id_rsa

# ssh known hosts
RUN sudo touch .ssh/known_hosts
RUN sudo chown hidetomo:hidetomo .ssh/known_hosts
RUN chmod 644 .ssh/known_hosts

# vim
RUN sudo apt-get -y install vim
COPY vimrc_simple .vimrc
RUN sudo tr \\r \\n <.vimrc> tmp && sudo mv tmp .vimrc
RUN sudo chown hidetomo:hidetomo .vimrc

# share
RUN mkdir share
VOLUME share

# common apt-get
RUN sudo apt-get -y install \
  ntp \
  unzip \
  bzip2 \
  gcc \
  git \
  less \
  subversion \
  wget

# git config
RUN git config --global user.email 'attyamunn@gmail.com'
RUN git config --global user.name 'hidetomo.watanabe'

# java
RUN sudo apt-get -y install python-software-properties software-properties-common
RUN sudo sh -c "echo 'oracle-java8-installer shared/accepted-oracle-license-v1-1 select true' | debconf-set-selections"
RUN sudo add-apt-repository -y ppa:webupd8team/java
RUN sudo apt-get update
RUN sudo apt-get -y install oracle-java8-installer
RUN sudo apt-get -y install oracle-java8-set-default

# mongo
RUN sudo apt-get -y install mongodb
RUN mkdir mongo
RUN mkdir mongo/db
RUN echo "export LC_ALL=C" >> .bashrc
ENV LC_ALL C

# preinstall
RUN mkdir works
COPY start.sh start.sh
RUN sudo tr \\r \\n <start.sh> tmp && sudo mv tmp start.sh
RUN sudo chown hidetomo:hidetomo start.sh
RUN chmod 644 start.sh
COPY install_sdk.sh install_sdk.sh
RUN sudo tr \\r \\n <install_sdk.sh> tmp && sudo mv tmp install_sdk.sh
RUN sudo chown hidetomo:hidetomo install_sdk.sh
RUN chmod 644 install_sdk.sh

# start
CMD ["/bin/bash", "./start.sh"]
